### ISSUE TITLE
Project / Gradle properties not getting picked up

### ISSUE THREAD

**Issue by rgoomar** [gradle/gradle-profiler#104]
I keep getting failures saying the property is not available on projects that have private credentials specified. They are already defined in my `~/.gradle/gradle.properties` file

It's when I have something like:
```
repositories {
	maven {
		credentials {
			username mavenuser
			password mavenpass
		}
		url "https://private-repo-url"
	}
}
```
I keep getting an error like so:
```
No such property: mavenuser for class: org.gradle.api.internal.initialization.DefaultScriptHandler
```
I tried passing in the credentials with `-D` and explicitly adding them in the command with something like `"build -Pmavenuser=X -Pmavenpass=Y"`.

**Comment by oehme** [comment]
The Gradle profiler uses an isolated user home by default. Either put your properties there or change it back to your shared user home using the `--gradle-user-home` option

**Comment by rgoomar** [comment]
Thanks! That fixed it. I didn't know that was an option based on the command line options listed in the README. I made this [pull request](https://github.com/gradle/gradle-profiler/pull/105) that adds it to the README.
