### ISSUE TITLE
Integration tests failing for maven and bazel

### ISSUE THREAD

**Issue by pvliss** [gradle/gradle-profiler#108]
Hello, 

First off, thank you for a great and invaluable tool. Used it for for profiling gradle builds for projects generated by JHipster and worked like a charm. 

Nevertheless, I had some issues which I will list separately(e.g. bumped into #43 myself), and after forking and trying to build locally the Maven and Bazel integration tests were failing as they seem to have become stale.

As it is seemingly a simple fix I was not sure if I should directly create a PR  or an issue first hence I went with the later. I have already done a fix(which also includes a minor improvement to avoid loading the report all the time)  and will send a PR asap.

Thanks again for a great tool :heart:

**Comment by oehme** [comment]
Thank you for fixing this!

**Comment by pvliss** [comment]
@oehme Glad to be of help
