### ISSUE TITLE
Question about different cache strategies in gradle profiler scenario file

### ISSUE THREAD

**Issue by maxim-pandra** [gradle/gradle-profiler#157]
Hello,

I'm using a gradle profiler and I want to measure clean build time. So, I think I should clean build caches before each execution.

Gradle profiler has multiple cache clearing strategies including:

- `clear-build-cache-before`: Deletes the contents of the build cache before the scenario is executed (`SCENARIO`), before cleanup (`CLEANUP`) or before the build is executed (`BUILD`).
- `clear-transform-cache-before`: Deletes the contents of the transform cache before the scenario is executed (`SCENARIO`), before cleanup (`CLEANUP`) or before the build is executed (`BUILD`).
- `clear-project-cache-before`: Deletes the contents of the .gradle and buildSrc/.gradle project cache directories before the scenario is executed (`SCENARIO`), before cleanup (`CLEANUP`) or before the build is executed (`BUILD`).

Unfortunately the difference between them is not clear for me.

Questions:

1. What is the difference between build and transform caches?
2. Should I also disable remote cache, or gradle profiler will disable remote cache automatically?

I also posted this question at stackoverflow: https://stackoverflow.com/questions/58303233/different-cache-strategies-in-gradle-profiler

**Comment by wolfs** [comment]
There is the build cache, as described [here](https://docs.gradle.org/current/userguide/build_cache.html). The `clear-build-cache-before` mutator affects this build cache.

The transforms cache is for the output of [artifact transforms](https://docs.gradle.org/current/userguide/artifact_transforms.html). It has nothing to do with the build cache and you probably don't need to clean it.

The project caches are used for caching internal Gradle data, like the task history. You probably also don't want to clean it for testing clean builds.

Note that you don't need to clean anything if you don't enable the build cache explicitly.

For more information about the Gradle directory layout see the [Gradle user manual](https://docs.gradle.org/current/userguide/directory_layout.html).
