### ISSUE TITLE
json parse error - Cannot open generated chrome trace in Windows platform

### ISSUE THREAD

**Issue by LionH** [gradle/gradle-profiler#159]
You can easily replicate the issue running the profiler with --profile chrome-trace and try to open the generated html on a Windows machine.
This is due to backslash on Windows path...
I've resolved this doing the following just before the parser parsing the json generated data:
```
eventData = eventData.replace(/\\/g, "/");
```
on function TraceEventImporter

**Comment by blindpirate** [comment]
Thanks @LionH ! Would you like to provide a PR?
