### ISSUE TITLE
Support ABI and non-ABI change for Kotlin files

### ISSUE THREAD

**Issue by JakeWharton** [gradle/gradle-profiler#17]

**Comment by oehme** [comment]
A PR would be very welcome.

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle-profiler/pull/71

Note that it's not perfect, as the method it adds is never called. So dexing will just ignore it. A more comprehensive solution would use the Kotlin compiler to actually parse and modify the source.
