### ISSUE TITLE
Can't profile cold daemon

### ISSUE THREAD

**Issue by oehme** [gradle/gradle-profiler#18]
The profiler always does at least one warmup build, making it impossible to measure a cold daemon, a.k.a. "first build" scenario using the tooling API invoker.

**Comment by oehme** [comment]
We could of course say "Use the no-daemon invoker", but that one can't be profiled atm, as the profiler control assumes a running daemon. Maybe we should improve that instead.

**Comment by adammurdoch** [comment]
I started adding support for profiling with `--no-daemon`. Currently it only works with yourkit. The idea is that this should also allow us to profile the daemon over its whole lifetime.

**Comment by oehme** [comment]
I've added --no-daemon support for JProfiler too and split out the "profile whole lifetime" story.
