### ISSUE TITLE
Release Gradle Profiler as a Java Library

### ISSUE THREAD

**Issue by cckroets** [gradle/gradle-profiler#185]
I would like to be able to depend on gradle-profiler from a Java project to automate benchmarking in a CI environment, without needing to open up a zip file to extract the executable / jar.

**Comment by wolfs** [comment]
Well, nobody stops you doing this. The released versions live on [repo.gradle.org](https://repo.gradle.org/gradle/webapp/#/artifacts/browse/tree/General/repo/org/gradle/profiler/gradle-profiler/0.9.1).

We actually [use in in the `gradle/gradle` build](https://github.com/gradle/gradle/blob/5d3460e54c085e5b38163f26ec4916df55943cce/subprojects/internal-performance-testing/internal-performance-testing.gradle.kts#L38-L40).

The API currently has its rough edges and there are no compatibility guarantees, though it works.

**Comment by cckroets** [comment]
Thanks for the quick reply. Looks like my problem was just not adding the gradle repository to my project.

```gradle
repositories {
   maven { url 'https://repo.gradle.org/gradle/repo' }
}
```
