### ISSUE TITLE
Set gradle argument to non-warm up build

### ISSUE THREAD

**Issue by doniwinata0309** [gradle/gradle-profiler#187]
Hi, i put tag on my gradle enteprrise by passing -Pbenchmarkid on the gradle args to filtering our benchmark build. However, the scan also tagged into warm-ups build, which make trends average seems to be wrong. 
Take example of folowing scenarios:
incremental_build_app {
    apply-abi-change-to = "app/src/main/java/com/myapp/android/util/ImageUtil.java"
    tasks = ["appentry:aGD"]
    gradle-args = ["-PbenchmarkId=incremental_build_app", "-Dandroid.databinding.incremental=true", "-Dandroid.databinding.incremental=true", "-Dkapt.incremental.apt=true", "-Dorg.gradle.daemon=true", "--info"]
    warm-ups = 1
}
I only want to set `-PbenchmarkId=incremental_build_app` on meassured build, not on warm ups build. Do you have any advice in this case ?

**Comment by oehme** [comment]
You can check the `org.gradle.profiler.phase` JVM argument, which is [added to each invocation](https://github.com/gradle/gradle-profiler/blob/8f9ea03a8153a682ead168a5e9a9c20f499523a3/src/main/java/org/gradle/profiler/BuildUnderTestInvoker.java#L35).
