### ISSUE TITLE
Applying non abi change to Kotlin source changes Java ABI

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle-profiler#212]
While this is a limitation of compilation avoidance, currently with `apply-non-abi-change-to` in the scenario file, Java ABI will be changed because `KotlinMetadata` annotation will change. This means that the change is not a non-ABI in a typical sense.

If  possible, adding a dummy method and modifying its body would be great.

**Comment by porcupine7** [comment]
Thanks for filing this bug. I wondered why there was no difference between `apply-abi-change-to` and  `apply-non-abi-change-to` in my kotlin module. This seems to be the reason.

**Comment by lptr** [comment]
@eskatos:

> I had a quick look, should be fairly simple, `beforeScenario()` would insert the dummy function, and `applyChangeTo()` would change the function body.

**Comment by eskatos** [comment]
Fixed by https://github.com/gradle/gradle-profiler/pull/215
