### ISSUE TITLE
Capturing build operations adds large build time overhead

### ISSUE THREAD

**Issue by lptr** [gradle/gradle-profiler#214]
It seems that when capturing build operations is enabled during a benchmark, builds run significantly slower. Here's a non-ABI change on Santa Tracker Kotlin without capturing build operations:

![image](https://user-images.githubusercontent.com/495366/87676876-6bb1b500-c779-11ea-9d21-c9a0280141f9.png)

Trimmed mean of 50% |   |   |  
-- | -- | -- | --
Scenario | Execution | Difference
0 – Baseline | 2,813 ms | 0 ms | 0.00%
2 – FS watching | 2,712 ms | -100 ms | -3.57%

And here is the same result with capturing a number of operations around snapshotting:

![image](https://user-images.githubusercontent.com/495366/87677774-6e60da00-c77a-11ea-8a77-8c5686fecc05.png)

Trimmed mean of 50% |   |   |  
-- | -- | -- | --
Scenario | Execution | Difference
0 – Baseline | 3,228 ms | 0 ms | 0.00%
2 – FS watching | 3,109 ms | -119 ms | -3.69%

There is a 12.4% increase at 400 ms when build operations are captured. However, with production builds we've seen far larger impacts at around 40%+.

**Comment by lptr** [comment]
The impact seems to be pretty uniform at least in all cases observed.

**Comment by lptr** [comment]
I was suspecting that maybe for some reason we are not visiting so much of the build operations if they are not observed, but we do visit even input files with no build operation tracing:

```text
org.gradle.api.internal.tasks.SnapshotTaskInputsBuildOperationResult.visitInputFileProperties(SnapshotTaskInputsBuildOperationType$Result$InputFilePropertyVisitor) SnapshotTaskInputsBuildOperationResult.java
com.gradle.scan.plugin.internal.b.u.a.h$a.a(h$d, boolean) SourceFile:183
com.gradle.scan.plugin.internal.b.u.a.h$a.a(h$d) SourceFile:177
com.gradle.scan.plugin.internal.b.u.a.h$a.a(h$a, h$d) SourceFile:47
com.gradle.scan.plugin.internal.b.u.a.h.a(h$a, c, SnapshotTaskInputsBuildOperationType$Details, SnapshotTaskInputsBuildOperationType$Result) SourceFile:211
com.gradle.scan.plugin.internal.b.u.a.h$$Lambda$408.finished(c, Object, Object)
com.gradle.scan.plugin.internal.j.a.f.a(b, c, Object, Object, Throwable) SourceFile:12
com.gradle.scan.plugin.internal.j.a.f$$Lambda$369.finished(c, Object, Object, Throwable)
com.gradle.scan.plugin.internal.j.a$c.finished(c, Object, Object, Throwable) SourceFile:154
com.gradle.scan.plugin.internal.j.a.a(c, Object, Object, Throwable) SourceFile:65
com.gradle.scan.plugin.internal.j.k.a(c, Object, Object, Throwable) SourceFile:58
com.gradle.scan.plugin.internal.j.c.a(BuildOperationFinishedNotification) SourceFile:103
com.gradle.scan.plugin.internal.j.g.a(BuildOperationFinishedNotification) SourceFile:48
com.gradle.scan.plugin.internal.j.g$$Lambda$467.accept(Object)
com.gradle.scan.plugin.internal.q.a$a.a() SourceFile:31
com.gradle.scan.plugin.internal.q.a$a.a(a$a) SourceFile:20
com.gradle.scan.plugin.internal.q.a.c() SourceFile:67
com.gradle.scan.plugin.internal.q.a$$Lambda$330.run()
java.lang.Thread.run() Thread.java:834
```

**Comment by lptr** [comment]
Something sinister is going on here.

With this version of Gradle Profiler, there is a distinct difference between running with build ops and without https://github.com/gradle/gradle-profiler/commit/c871125d5e37f4ff7d4a19fa0045198cba6a3eff

- without build ops: 616.56 ms
[benchmark-no-build-ops-old-profiler.html.zip](https://github.com/gradle/gradle-profiler/files/5174277/benchmark-no-build-ops-old-profiler.html.zip)
- with build ops: 923.00 ms 
[benchmark.html-with-build-ops-old-profiler.zip](https://github.com/gradle/gradle-profiler/files/5174280/benchmark.html-with-build-ops-old-profiler.zip)

However, with the latest master there is no difference: https://github.com/gradle/gradle-profiler/commit/449c02cab455ebdee84759dbaab7b0d15bf975b8

- without build ops: 820.65 ms 
[benchmark.html-no-build-ops-new-profiler.zip](https://github.com/gradle/gradle-profiler/files/5174299/benchmark.html-no-build-ops-new-profiler.zip)
- with build ops: 814.75 ms 
[benchmark.html-with-build-ops-new-profiler.zip](https://github.com/gradle/gradle-profiler/files/5174296/benchmark.html-with-build-ops-new-profiler.zip)

Something happened between these commits: https://github.com/gradle/gradle-profiler/compare/c871125d5e37f4ff7d4a19fa0045198cba6a3eff...449c02cab455ebdee84759dbaab7b0d15bf975b8

**Comment by lptr** [comment]
I cannot actually reproduce the problem. I ran a bunch of tests with different versions of the profiler, but couldn't reproduce a consistent pattern:

Commit ID | without build ops | with build ops
-- | -- | --
@c871125d | 650 ms | 1,066 ms
master@449c02c | 872 ms | 848 ms
@6240afce | 697 ms | 973 ms
@f6939bbe | 884 ms | 890 ms
@a712392a | 832 ms | 896 ms
@66e52c9e | 882 ms | 1,048 ms
@0c03ecb6 | 846 ms | 1,010 ms

**Comment by lptr** [comment]
OK, now I somehow can reproduce it with `master`:

![image](https://user-images.githubusercontent.com/495366/92256451-0a35d900-eed4-11ea-9aee-5af6eb86be33.png)

As well as with c871125d5e37f4ff7d4a19fa0045198cba6a3eff:

![image](https://user-images.githubusercontent.com/495366/92256630-3cdfd180-eed4-11ea-9fe1-e8ae76dd8501.png)

**Comment by lptr** [comment]
I ran the last tests that _do_ reproduce the problem on Linux. Maybe this somehow only affects Linux?

**Comment by lptr** [comment]
I can now reproduce this with macOS with OpenJDK 11: 
![image](https://user-images.githubusercontent.com/495366/92576331-b50a1680-f289-11ea-9b04-462c2a6f9b72.png)

No idea why I couldn't do it before.

**Comment by lptr** [comment]
Looks like the overhead depends not on the operation types measured, but on the actual number of operations captured:

![image](https://user-images.githubusercontent.com/495366/92592825-72076d80-f2a0-11ea-9b34-1f482bee3eaf.png)

**Comment by lptr** [comment]
OK, so now I'm NOT able to reproduce it anymore. I did not change anything...

![image](https://user-images.githubusercontent.com/495366/92594416-0541a280-f2a3-11ea-8b6b-4038cad98377.png)

**Comment by lptr** [comment]
The gaps seem to be reproducible on Linux (both with Java 8 and 11), and the size of the gap apparently depends on the number of operations watched:

![image](https://user-images.githubusercontent.com/495366/92605510-1b0a9400-f2b2-11ea-843f-6a311249ceba.png)

The most likely cause for the gap is that we are adding on `BuildOperationListener` per watched operation, and that's costly to invoke. We can thus reduce the gap by only registering a single listener instead.

None of the above explains why the gap _sometimes_ disappear on macOS though...

**Comment by lptr** [comment]
I can also reproduce the difference with the Gradle build, and it shows that the overhead is indeed proportional to both the number of build operation types measured as well as the raw number of build operations happening:

![image](https://user-images.githubusercontent.com/495366/92610553-1b0d9280-f2b8-11ea-8ce9-7100b8f44c66.png)

**Comment by lptr** [comment]
This is weird. It seems that when we are benchmarking with build operations captured, we register multiple `BuildOperationListener`s and handle the events as they arrive.

However, for the `:chrome-trace` subproject we seem to have a separate spooling mechanism that writes the events asynchronously to a file.

**Comment by wolfs** [comment]
> This is weird. It seems that when we are benchmarking with build operations captured, we register multiple BuildOperationListeners and handle the events as they arrive.

We handle the events when they arrive, but only write them to disk at the end. That is why we shouldn't need to use the spooling from the chrome trace.
