### ISSUE TITLE
Consider publishing binaries

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-profiler#216]
This tool is great! The hassle of having to clone, build, and PATH it to run even quick tests is a lot of friction though. Would you consider publishing binaries?

This would be particularly useful for CI environments to run continuous benchmarking.

Some options:

- GitHub releases that can be downloaded directly
- Established package managers, such as homebrew for macOS

I'd be happy to try to help with PRs for preparing this, but obviously only gradle maintainers can publish releases.

**Comment by gildor** [comment]
Binaries are available in this repo:
https://repo.gradle.org/gradle/ext-releases-local/org/gradle/profiler/gradle-profiler/0.12.0/gradle-profiler-0.12.0.zip

But publish it to brew and sdkman would be a lot better (to get proper installation, integration with PATH)

**Comment by wolfs** [comment]
@ZacSweers Given that there are already published binaries, what else do you need? What could you create a PR for?

**Comment by ZacSweers** [comment]
That's a slight improvement over cloning and building, but I think publishing to an established package manager would still be a worthwhile endeavor to make consumption frictionless

**Comment by runningcode** [comment]
Thanks @wolfs: https://github.com/sdkman/sdkman-db-migrations/pull/300

**Comment by wolfs** [comment]
Gradle profiler is now live on SDKman: 
![image](https://user-images.githubusercontent.com/423186/88302528-3cb1bb00-cd06-11ea-8a70-fb524c69b843.png)

**Comment by ZacSweers** [comment]
Just tested it out on homebrew as well since it was merged today, worked like a charm. I think this can be closed now, thanks for being open to it!

![image](https://user-images.githubusercontent.com/1361086/88443084-f2ebd200-cde4-11ea-9522-3c4c55d3c8e8.png)
