### ISSUE TITLE
Expose project directory in BuildContext

### ISSUE THREAD

**Issue by lptr** [gradle/gradle-profiler#231]
This would be useful for mutators.

**Comment by wolfs** [comment]
I am not sure the `BuildContext` should expose the project directory. The project directory should be something which stays the same during the performance iterations. The project directory and the Gradle user home is something we expose when instantiating the mutator before running all the iterations.

**Comment by lptr** [comment]
Right now `BuildContext` extends `ScenarioContext`. I think we should remedy that, and instead either add `BuildContext.getScenarioContext()` or pass `ScenarioContext` along with `BuildContext`. Either way, I think we should expose the whole `InvocationSettings` object in `ScenarioContext` (or pass/expose an `InvocationContext` object with similar data).

**Comment by wolfs** [comment]
So you mean that a `BuildMutator` instance should live much longer than for only one scenario and should reset itself in `beforeScenario`?

I had more in mind that for each scenario Gradle profiler creates a new `BuildMutator` for the invocation settings.

**Comment by lptr** [comment]
Let's revert this for now.

**Comment by lptr** [comment]
Reverted in #235.
