### ISSUE TITLE
Document how to use gradle-profiler with build scans

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle-profiler#24]
Add a section to the readme about profiling with build scans similar to JFR and YourKit.

**Comment by eriwen** [comment]
Would love to see this done so I can tweet this project soon :)

**Comment by pioterj** [comment]
@oehme said he wanted to polish the readme anyway so this is a good opportunity to do this.

**Comment by oehme** [comment]
I updated the readme, please have a look.

**Comment by pioterj** [comment]
Looks good to me. What do you think about also including a screenshot with the timeline view?

**Comment by oehme** [comment]
Honestly I feel that it is already getting pretty long. If we want to add screenshots, then we should probably switch over to using the repository's wiki.
