### ISSUE TITLE
Add support for recording VisualVM compatible profiling sessions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-profiler#25]
See https://github.com/visualvm/visualvm.src/issues/17

The sampler is available in the Netbeans repository: http://bits.netbeans.org/nexus/content/groups/netbeans/

`org.netbeans.api:org-netbeans-modules-sampler:RELEASE82`

```
paul@chestnut $ java -jar org-netbeans-modules-sampler-RELEASE82.jar
Usage: <port> <snapshot.npss>

First of all start your application with following parameters:
  -Dcom.sun.management.jmxremote.authenticate=false
  -Dcom.sun.management.jmxremote.ssl=false
  -Dcom.sun.management.jmxremote.port=<port>
Then you can start this sampler with correct port and file to write snapshot to.
```

VisualVM can then open `*.npss` files

**Comment by oehme** [comment]
I'm going to close this since JFR provides much more reliable data and is free to use in a development environment (and soon will be open source). So there is really no need to add more options here I think
