### ISSUE TITLE
Support projects that require an init-script

### ISSUE THREAD

**Issue by pgratton** [gradle/gradle-profiler#27]
- gradle-profiler injects its own init-script, so adding one to your scenario file via "gralde-args" will fail.

ie:
```
doProfile {
    tasks = ["install"]
    gradle-args = ["--init-script", "/path/to/my/init/script/init.gradle"]
}
```
- the probe from GradleVersionInspector will also fail since it does not run the application's init-script, but injects its own (https://github.com/gradle/gradle-profiler/blob/master/src/main/java/org/gradle/profiler/GradleVersionInspector.java#L91

**Comment by oehme** [comment]
Gradle supports adding mutliple init scripts, so that should not be a problem. We could adjust the version inspector to take into account the arguments passed for each scenario.

Use the profiler's `--gradle-user-home` option and put your init script there.

**Comment by oehme** [comment]
Closing since projects should not require an init script just to start up. Init scripts are meant to be decorative in nature (e.g. adding logging/instrumentation/user preferences/environment overrides). Any configuration that is mandatory should be part of the settings/build script.
