### ISSUE TITLE
Add option to specify baseline for the scenario

### ISSUE THREAD

**Issue by Mishkun** [gradle/gradle-profiler#272]
Right now,  baseline scenario is selected [in two ways](https://github.com/gradle/gradle-profiler/commit/9c8f7bde8f2c06fbdd9f7026f6bc99bcf8e2ba69#diff-fee50d590e8b685d444d8b90b0276502R418-R423). If there are multiple build tools, you can select, which one would be the baseline. If there is one build tool, first scenario is selected.

When optimizing my project's build speed, I ran multiple scenarios side-by-side, with or without the change. I would like to have possibility to provide name of the scenario to be selected as basline like this:
```hocon
// file profile.scenarios

some_build_config {
 // scenario definition
}

some_build_config_with_tweaks {
  // scenario definition
  baseline = "some_build_config"
}
```

**Comment by lptr** [comment]
The baseline detection is now removed, and you have the option to choose the baseline in the HTML report. The CSV reports don't include any comparison information anymore.

Note that if you have multiple build tools (or Gradle versions) in a single benchmark, the HTML report will automatically select the first scenario as the baseline, but that's easy to change.
