### ISSUE TITLE
Statistics information was removed from benchmark.csv 

### ISSUE THREAD

**Issue by maxim-pandra** [gradle/gradle-profiler#281]
In gradle-profiler 0.15.0 statistics information was removed from benchmark.csv

What was wrong with the statistics?

We were relying on it a little.

**Comment by lptr** [comment]
Hi @maxim-pandra. There was quite a bit of overlap between the purposes of the different reports. Now we have a more clear-cut division of responsibilities:

- CSV reports have the raw data you can import in your own app or a spreadsheet application (it should be easy to calculate means and deviations there),
- HTML report is for the human to look at, so we provide calculated values and the concept of a (selectable) baseline in that report, along with a bunch of metadata. Now we also add a number of tools in that report to play around with the data.
