### ISSUE TITLE
CSV report no longer produces mean, median and other calculated stats

### ISSUE THREAD

**Issue by abhishekBansal** [gradle/gradle-profiler#287]
I updated `gradle-profiler` version to `0.15.0` from `0.12.0`. I noticed that build time calculations such as mean, median, standard error etc are no longer being reported in `CSV` report. 
command that I use for build benchmarking is rather simple one
```bash
 gradle-profiler --benchmark --scenario-file build_performance.scenarios --warmups 1 --iteration 5 
```
Here is my build scenario file
```
# Can specify scenarios to use when none are specified on the command line
default-scenarios = ["assemble"]

# Scenarios are run in alphabetical order
assemble {
    # Show a slightly more human-readable title in reports
    title = "Clean Build Debug"
    # Run the 'assemble' task
    tasks = ["assembleDebug"]
    cleanup-tasks = ["clean"]
}
```

**Comment by plastiv** [comment]
Hi! The change was intentional https://github.com/gradle/gradle-profiler/issues/281
