### ISSUE TITLE
Chrome trace data with backslash cannot be opened on macOS

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-profiler#293]
I'm assuming that Chrome just won't open those chrome traces on other operating systems as well. The key point here is chrome trace generated on Windows most likely will contain backslash because of the file path separator. This causes an error when opening in the lines of "Unexpected token...".

I was able to "fix" the chrome trace by doubling all backslash in the embedded JSON data. It would be much better if the profiler could generate valid JSON data without needing manual editing.

**Comment by lptr** [comment]
Thanks @lacasseio. Would you care for submitting a PR to fix this?

**Comment by ianbrandt** [comment]
I'm finding Chrome traces generated on Windows also don't open on Windows unless all the contained backslashes are replaced with forward slashes.

Gradle Profiler version 0.18.0
Google Chrome version 104.0.5112.81 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/709570/184724976-b08b5d4f-1c0b-4787-b85e-f05e61401fb4.png)

**Comment by ianbrandt** [comment]
I can confirm this is resolved for me with 0.20.0. Thanks!
