### ISSUE TITLE
chrome-trace generates file that can't be loaded into browser

### ISSUE THREAD

**Issue by tobias-** [gradle/gradle-profiler#303]
After running gradle-profiler with chrome-trace I get an html-file which I cannot load into browser (blank page)

If I strip away all but the json (via grep or editor), I can go to chrome://tracing and load it.

I suspect other people do not have this problem or there would be an issue for it and that it is related to the browser (tried with Chromium & Brave), but having the json file would help me.

**Comment by mathjeff** [comment]
I think I'm observing the same problem.

When I try to open, for example, `profile-out-2/6.8.1-trace.html`, in Chrome, I also see a blank page. Then when I push "ctrl-shift-I" to view the Console, I see this error:

```
Uncaught TypeError: document.registerElement is not a function
    at 6.8.1-trace.html:4719
    at 6.8.1-trace.html:4734
```
