### ISSUE TITLE
Is the build cache used when benchmarking?

### ISSUE THREAD

**Issue by BoD** [gradle/gradle-profiler#319]
I am sorry as this is not an issue but a question, but I don't know where else to ask!

I was wondering if by default when running with `--benchmark` without a specific scenario whether the gradle build cache is used?  Maybe this could be clarified in the README.

Thanks a lot!

**Comment by lptr** [comment]
It depends on the build you are measuring and the command line you use. If your build has a `gradle.properties` with `org.gradle.caching=true` in it, then it will be enabled unless your benchmark also passes the `--no-build-cache` option.

**Comment by BoD** [comment]
Thank you so much! 🙏

**Comment by BoD** [comment]
Actually `--no-build-cache` doesn't seem to be recognized?

**Comment by lptr** [comment]
You have to pass it via `gradle-args` in a scenario, check out https://github.com/gradle/gradle-profiler#advanced-profiling-scenarios.
