### ISSUE TITLE
0.16.0 prebuilt artifact link 404s

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-profiler#332]
The link points to nowhere now: https://repo.gradle.org/gradle/ext-releases-local/org/gradle/profiler/gradle-profiler/0.16.0/gradle-profiler-0.16.0.zip

**Comment by ZacSweers** [comment]
Looks like it's now https://repo.gradle.org/artifactory/ext-releases-local/org/gradle/profiler/gradle-profiler/0.16.0/gradle-profiler-0.16.0.zip?

**Comment by wolfs** [comment]
This was a problem with repo.gradle.org and works now again.
