### ISSUE TITLE
Make chrome-trace work with 4.0

### ISSUE THREAD

**Issue by oehme** [gradle/gradle-profiler#34]
The build operation interfaces changed in 4.0.

**Comment by jjohannes** [comment]
- Changed the implementation to work with 4.0: a19a03d3179373c97a212e658e7f55a2d4cb3234
- Added backwards-compatibility for 3.5: 8e4af31ecc42cdf7a44ae8d8efd7abf60cb4f90f ea16273f799aa099842e435828367f30b14c7413

**Comment by oehme** [comment]
It would be great if you could extract these compatibility concerns into their own classes, so we don't have all this code in a single "TracePlugin" class. It's getting pretty hard to read.
