### ISSUE TITLE
Could not get unknown property 'githubToken' error on master

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle-profiler#344]
When checking out a clean master of this project I get the following error when running `./gradlew tasks`.

> Could not get unknown property 'githubToken' for root project 'gradle-profiler' of type org.gradle.api.Project.

See build scan: https://ge.gradle.org/s/suzx5lck45t4w/failure#1

Commenting out line 176 of the root `build.gradle.kts` fixes the issue.

**Comment by wolfs** [comment]
Thank you for reporting. I think https://github.com/gradle/gradle-profiler/pull/345 should fix it. I suppose you meant running `tasks` not `help`, at least that was what it says in the build scan - I edited your issue description. For `help`, the build doesn't fail for me.

**Comment by runningcode** [comment]
Thanks for the quick fix !
