### ISSUE TITLE
apply-abi-change-to results in an error

### ISSUE THREAD

**Issue by MatthewPageCS** [gradle/gradle-profiler#41]
When I use the `apply-abi-change-to` mutation, I get an error because the method it adds is non-static, but is referenced statically.

I've fixed this on my own version of the repo by adding a "STATIC" modifier to ApplyAbiChangeToJavaSourceFileMutator.java line 34, and it works fine.

**Comment by athornz** [comment]
I'm also getting the same error.

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle-profiler/commit/f7bb981df59ba19d6e2a7ce40936ffcd64c0fb06
