### ISSUE TITLE
unable to skip warmup builds despite --warmups=0

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle-profiler#43]

**Comment by oehme** [comment]
Could you elaborate what use case you have for 0 warmups?

**Comment by wisechengyi** [comment]
Sure! In a separate thread where we were trying to figure out what the performance issue is for gradle after `git clean -fdx` in the android repo. The issue only occurs on the first run, because the second run will be all up to date. In this case, having 'clean' task as the clean up task does not work because `./gradlew clean` isn't the same as `git clean -fdx`

It does make sense to me that `warmups` has a non zero default value, but since it is an option, specifying `--warmups=0` should work as expected as well.

**Comment by oehme** [comment]
I remember the problem you were looking for was in `buildSrc`. The Gradle profiler will already start up Gradle to determine what version you are running on and what extra JVM args your build specifies. So `buildSrc` will already be warmed up, even before the first "warmup run".

I think for analysing this special case, you might want to add the agentpath for JProfiler/YourKit to the Gradle JVM args by hand and profile "the old fashioned way". The Gradle profiler isn't really suited for this kind of "first use" analysis at the moment.

**Comment by wisechengyi** [comment]
I understand. Although my second point should be still valid, i.e. it makes sense for warmup to have non zero default, but there is no need to force warmup runs, i.e. `--warmups=0`should not surprise people.

**Comment by charlesritchea** [comment]
@oehme My use case is simple. My build takes a long time (long running e2e test), so I don't want to run it more than once.

**Comment by blundell** [comment]
getting the error with:

```
  daemon = cold
  warm-ups = 0
```
