### ISSUE TITLE
What build operations are measured-build-ops  supporting?

### ISSUE THREAD

**Issue by NightXlt** [gradle/gradle-profiler#435]
I notice that `measured-build-ops` support filling in build operation class, like this way.

```java
measured-build-ops = ["org.gradle.api.internal.tasks.SnapshotTaskInputsBuildOperationType"] // see --measure-build-op
```

Is there any way to know more about build operation type, because I wanna profile some operation like project total tasks execution time, not simply plus tasks time of project. Any doc or source code guidance about build operation would be appreciated.

**Comment by lptr** [comment]
Not at this time. Build operations are an internal feature of Gradle. You can look at all the types implementing `org.gradle.internal.operations.BuildOperationType` for a specific Gradle version, but there is no guarantee that the next version will have the same operations.
