### ISSUE TITLE
IDE sync profiling incompatible with Android Studio Electric Eel Canary 8

### ISSUE THREAD

**Issue by mikejuyoon** [gradle/gradle-profiler#437]
We've been using Gradle-profiler to benchmark sync times with different Android Studio versions. Recently when we tried to benchmark Android Studio Electric Eel  (2022.1.1) Canary 8, we found a couple errors due to incompatibility. 
Thank you @rogerhu for the help with this investigation

**Versions:**
- [Android Studio Electric Eel (2022.1.1) Canary 8](https://developer.android.com/studio/archive](https://developer.android.com/studio/archive)
- Gradle Profiler version 0.18.0 or 1.19.0 (master)

**Errors**
1. `java.lang.ClassNotFoundException: com.intellij.openapi.util.SystemInfoRt`
    - Stack Trace: [https://gist.github.com/mikejuyoon/323f7ebf6868e864fb112c4adfe89307](https://gist.github.com/mikejuyoon/323f7ebf6868e864fb112c4adfe89307)
    - A possible fix: [https://github.com/gradle/gradle-profiler/pull/436/commits/d1fcb1bf1cd7839f3d50c620bcef5ae6153fc898](https://github.com/gradle/gradle-profiler/pull/436/commits/d1fcb1bf1cd7839f3d50c620bcef5ae6153fc898)
2.  Bigger, trickier issue: `java.lang.IncompatibleClassChangeError: Method 'com.intellij.util.messages.MessageBusConnection com.android.tools.idea.gradle.project.sync.GradleSyncState.subscribe(com.intellij.openapi.project.Project, com.android.tools.idea.gradle.project.sync.GradleSyncListener)' must be InterfaceMethodref constant`
    - Stack Trace: https://gist.github.com/mikejuyoon/e9ccfd98e4b6d3854ebd90e725c4fd00
    - Looks like the Android plugin source have changed on Android Studio EE but not in the Jetbrains code. So there is API incompatibility. i.e:
        - [GradleSyncState](https://github.com/JetBrains/android/blob/master/android/src/com/android/tools/idea/gradle/project/sync/GradleSyncState.kt#L87) in Jetbrains/android vs: Android Studio's [GradleSyncStateImpl](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:project-system-gradle/src/com/android/tools/idea/gradle/project/sync/GradleSyncStateImpl.kt?q=GradleSyncState&ss=android-studio%2Fplatform%2Ftools%2Fadt%2Fidea)
    - We have a temporary fix, only to get Gradle profiler working with AS EE. Will likely break on other AS. We used the android.jar packaged with AS EE and included it into `org.jetbrains.android` module library when building gradle profiler. See: https://github.com/gradle/gradle-profiler/commit/e8d21ad54c542b90389a9526a4cb0b51c112ef40

**Comment by rogerhu** [comment]
I think you also want to remove the `android` plugin (https://github.com/gradle/gradle-profiler/blob/ee94b3bd0902fe68450422b72c7d796870a8e37e/subprojects/studio-plugin/build.gradle.kts#L49)here:


```
 {
    // disable android plugin so it can be pulled from the android.jar for Electric Eel
    plugins.set(listOf("java", "gradle"))
```

And add the `android.jar` and `libstudio.proto.jar` that gets published from an Android Studio version:

```
wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.1.1.8/android-studio-2022.1.1.8-mac.zip
unzip -o -j android-studio-2022.1.1.8-mac.zip -d . "Android Studio Preview.app/Contents/plugins/android/lib/libstudio.proto.jar" libstudio.proto.jar
unzip -o -j android-studio-2022.1.1.8-mac.zip -d . "Android Studio Preview.app/Contents/plugins/android/lib/android.jar"
```

**Comment by asodja** [comment]
Thanks for reporting the issue and finding potential solutions.

The first solution might make sense. For the second fix, I would like to avoid depending directly on jars though. I think we could resolve the Android Studio version somehow and then use some reflection if nothing else is possible.

**Comment by mikejuyoon** [comment]
@asodja thanks for taking a look! 

> It's very likely also that we just need to update IntelliJ version we depend on to make it compatible with Android Studio Electric Eel.

I've tried this and didn't work. modified [this line](https://github.com/gradle/gradle-profiler/blob/a990b3a0fcb55c4b450322dc8b16e5e6503a0032/subprojects/studio-plugin/build.gradle.kts#L44) to `2022.1.3` ([The IDEA version that Electric Eel is based on](https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2022)) 
I think this is because the android.jar has actually diverged quite a bit. 
e.g. Android Studio has [GradleSyncStateImpl](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:project-system-gradle/src/com/android/tools/idea/gradle/project/sync/GradleSyncStateImpl.kt?q=GradleSyncState&ss=android-studio%2Fplatform%2Ftools%2Fadt%2Fidea) but the latest IntelliJ codebase doesn't have that file

**Comment by mikejuyoon** [comment]
Also, let me know if you would rather open a new issue for this, but I discovered that Gradle Profiler is incompatible with Android Studio Chipmunk as well. The error is similar to what we saw on EE, but the patch we used for EE didn't work with Chipmunk
Logs:
* Running with gradle profiler 0.18.0: https://gist.github.com/mikejuyoon/609ac8c13b782c34b1422c801f0e683d 
* Running with patched version of gradle profiler (for EE): https://gist.github.com/mikejuyoon/60811876d570d4c90709f20880870c1e

**Comment by asodja** [comment]
Thanks @mikejuyoon for checking it. I checked Chipmunk and Dolphin and the solution with reflection works also for these two.

**Comment by mikejuyoon** [comment]
thanks for addressing this @asodja !
I pulled latest master with #439, unforunately I'm getting errors when running gradle profiler with the following versions of Android studio:
* AI-211.7628.21.2111.8309675 = 2021.1.1.23 = Bumblebee (2021.1.1) Patch 3
* AI-212.5712.43.2112.8609683 = 2021.2.1.15 = Chipmunk (2021.2.1) Patch 1

but Electric Eel is now working 🥳 

Heres are some logs for running against chipmunk: https://gist.github.com/mikejuyoon/4cbb3a012337d96d5aac4f72722f87db
both Chipmunk and Bumblebee are failing with :
```
Error: Could not find or load main class com.intellij.idea.Main
Caused by: java.lang.ClassNotFoundException: com.intellij.idea.Main
```

**Comment by asodja** [comment]
Hmm, the error is because nothing is on a classpath. I changed the logic so we don't have hardcoded libraries that should be added to a AS classpath, but are now parsed from `bin/studio.sh` file. So it needs some adjustments. Thanks for the report

**Comment by asodja** [comment]
@mikejuyoon I believe this will fix it: https://github.com/gradle/gradle-profiler/pull/442, if you could maybe try that with `Bumblebee` and `Chipmunk`.

**Comment by mikejuyoon** [comment]
@asodja 🎉  i checked the following versions with your branch and successfully measured sync!
Thank you for the fix!
```
AI-221.5921.22.2211.8786657 = 2022.1.1.8 = Electric Eel (2022.1.1) Canary 8
AI-211.7628.21.2111.8309675 = 2021.1.1.23 = Bumblebee (2021.1.1) Patch 3
AI-212.5712.43.2112.8609683 = 2021.2.1.15 = Chipmunk (2021.2.1) Patch 1
```
