### ISSUE TITLE
Adding a Build Scan tag to only the measured builds

### ISSUE THREAD

**Issue by blundell** [gradle/gradle-profiler#453]
You can create scenario and add a build scan tag (or value) like this:

```
gradle-args = [
    "-Dscan.tag.MY_TAG",
    "-Dscan.value.MY_VALUE=Hello World",
  ]
```
(combined with `--profile buildscan`)

But this is applied to all build scans for all builds, i.e. it includes the warm up builds.

I would like to add a tag/value just to the measured builds. This way I can leverage the 'search' of the Gradle Enterprise interface, but more importantly I can use the Performance tab to see aggregate stats (https://my-gradle-enterprise-host.biz/scans/performance).

**Comment by gabrielfeo** [comment]
Are you using [`buildScan.publishAlways`](https://docs.gradle.com/enterprise/gradle-plugin/api/com/gradle/scan/plugin/BuildScanExtension.html#publishAlways())? By default, Profiler doesn't record even scans of warm-up builds, only measured ones.

**Comment by blundell** [comment]
Ah yes, we have a `publishAlwaysIf` that is being triggered `true` :-) thanks.

I still think warmup buildscans are valuable, but looks like I can control it myside now 👍
