### ISSUE TITLE
“--buildscan-version” flag doesn’t override the buildscan plugin version used by profiler

### ISSUE THREAD

**Issue by kenyee** [gradle/gradle-profiler#454]
We're using an older version of the GE server and get this error when running gradle profiler when trying to upload buildscans because the gradle profiler is always a bit ahead of our updates:
```
The request was rejected.
Gradle Enterprise plugin version 3.10.2 is newer than the newest version supported by Gradle Enterprise 2022.1.1 which is 3.9. Please update to a newer version of Gradle Enterprise.
```

I found this flag in the integration tests: https://github.com/gradle/gradle-profiler/blob/cd4881ceb74b7c2c14f60c58c18d2239157f172b/src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy

but it doesn't seem to work even though in the profiler.log, it says:
Using build scan plugin 3.6
when I pass it as --buildscan-version 3.6

I also found this old closed issue where it was profiler supposedly doesn't override the buildscan plugin version if it's set already, but it still seems to: https://github.com/gradle/gradle-profiler/issues/58

**Comment by asodja** [comment]
Checking the code, I am not sure where `gradle-profiler` would apply `3.10.2`. Maybe I missed something, but it looks to me gradle-profiler applies lower versions [here](https://github.com/gradle/gradle-profiler/blob/3f688b1eb8041c7068da74d160e6bc88c93bd4ca/src/main/java/org/gradle/profiler/buildscan/BuildScanProfiler.java#L19).

Other than that I think you are right, we probably should check [here](https://github.com/gradle/gradle-profiler/blob/3f688b1eb8041c7068da74d160e6bc88c93bd4ca/src/main/java/org/gradle/profiler/DefaultGradleBuildConfigurationReader.java#L43) also if new plugin `com.gradle.enterprise` is applied.

**Comment by kenyee** [comment]
Thanks..I was a bit puzzled on how 3.10.2 is being applied too...doesn't seem to be anywhere in this repo.
We're using 3.6 in our project but will update when we upgrade our GE server.

The current gradle profiler code should be already using the applied plugin according to that other issue/PR I linked.  And --buildscan-version should allow us to force an override but doesn't 🤔

**Comment by kenyee** [comment]
FYI, what we've been doing to work around this is patch the latest release to do this to src/main/java/org/gradle/profiler/buildscan/BuildScanProfiler.java
```
-            if (buildConfiguration.getGradleVersion().compareTo(GRADLE_5) < 0) {
-                gradleArgs.add("-Dscan");
-            } else {
-                gradleArgs.add("--scan");
-            }
+            System.out.println("OVERRIDE, not passing --scan to avoid Profilers build scanner (use our own)");
+//            if (buildConfiguration.getGradleVersion().compareTo(GRADLE_5) < 0) {
+//                gradleArgs.add("-Dscan");
+//            } else {
+//                gradleArgs.add("--scan");
+//            }
```

If we could disable that arg via a gradle-profiler command line, it would also work for us.  Would that be a better solution?

**Comment by kenyee** [comment]
We found another workaround of forcing the version:
```
            configurations.getByName("classpath").resolutionStrategy {
                val version = ArtifactUtils.getArtifactVersion<GradleEnterpriseExtension>()
                force("com.gradle:gradle-enterprise-gradle-plugin:$version")
            }
```
so we don't need the fork, but the buildscan URL is not printed in the summary when a scenario is completed (probably because the code expects a different version of the buildscan plugin)?
Thought it was worth mentioning if anyone hits this before an official fix is available...

**Comment by asodja** [comment]
Thanks for finding a workaround. Yeah, it seems 3.10.2 is the auto-applied version from Gradle when `--scan` is used. So it seems Gradle overrides any version set by the gradle-profiler.

**Comment by kenyee** [comment]
Probably worth getting rid of all the old cruft code that doesn't do it properly in gradle-profiler and either documenting this workaround or using it?

**Comment by asodja** [comment]
I think https://github.com/gradle/gradle-profiler/pull/455 fixes all issues so it works as expected. If you have time, feel free to test it.
