### ISSUE TITLE
Fix TC pipeline after CI infrastructure changes

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle-profiler#467]
After we went with Apple M1s  vs. Intel  as default, the pipeline started failing.

https://builds.gradle.org/buildConfiguration/GradleProfiler_MacOSJava8/60579058?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Comment by blindpirate** [comment]
Fixed by https://github.com/gradle/gradle-profiler/pull/468
