### ISSUE TITLE
Fix Intel-Mac / Java 8 pipeline

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle-profiler#474]
Mysterious errors are happening in [this](https://builds.gradle.org/buildConfiguration/GradleProfiler_MacOSJava8/60607566?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true#%2F.teamcity%2Fproperties) pipeline.
A bit of investigation is required to find out what's happening.

@blindpirate can you have a look, as you might encountered this issue already. Thanks!

**Comment by blindpirate** [comment]
There is an issue open: https://github.com/gradle/gradle-profiler/issues/469
