### ISSUE TITLE
Gradle profiler may cause IDE deadlocks

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle-profiler#496]
See https://issuetracker.google.com/283471987 for more info

Waiting in [AndroidStudioSystemHelper](https://github.com/gradle/gradle-profiler/blob/e2ca5f44d135c89b7bdc433261cef05cfa38203d/subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java#L92) may cause deadlock:
```
 DumbService.getInstance(project).runReadActionInSmartMode(() -> {
            IdeFrame frame = WindowManagerEx.getInstanceEx().findFrameFor(project);
            StatusBarEx statusBar = frame == null ? null : (StatusBarEx) frame.getStatusBar();
            if (statusBar != null) {
                statusBar.getBackgroundProcesses().forEach(it -> waitOnProgressIndicator(it.getSecond()));
            }
        });

 private static void waitOnProgressIndicator(ProgressIndicator progressIndicator) {
        wait(WAIT_ON_PROCESS_SLEEP_TIME, progressIndicator::isRunning);
    }

    private static void wait(long sleepMillis, Supplier<Boolean> whileCondition) {
        while (whileCondition.get()) {
            try {
                Thread.sleep(sleepMillis);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
```

The following execution is possible:
- gradle-profiler holds the read lock and is blocked waiting for background processes to finish
- the EDT is trying to start a write action but is blocked until 1 finishes
- since there is a pending write action, all other new read actions are blocked, thus various background processes are unable to finish (thereby blocking 1 forever).

Can we please move waiting outside of the read action?

**Comment by akerimsenol** [comment]
I had a repro project for this earlier: https://github.com/akerimsenol/giraffe.profiler.hang.repro/commits/main

**Comment by asodja** [comment]
Fix for deadlock probably fixes also https://github.com/gradle/gradle-profiler/issues/480
