### ISSUE TITLE
Add build operation signals to YourKit snapshots

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle-profiler#50]
The snapshot obtained with the yourkit option contains a profile of the warmup runs and the build itself. This is not a huge issue in itself, but makes it hard to focus on one single build and identify specific segments of the build.

For context, I wanted to profile the execution of a particular task, so I got the gradle profiler to give me both the chrome trace and the yourkit snapshot, hoping that they would use the same time scale and I could use the trace to find the section I wanted in the snapshot. And that sort of worked, but I had to add up execution times to figure out the segment that I wanted in the snapshot.

**Comment by oehme** [comment]
It doesn't profile warmups, you only get telemetry for warmups. That's normal, both Yourkit and JProfiler collect telemetry as soon as they are loaded. The actual CPU and memory hotspots are only from the profiled run.

@IngoKegel is there some way to get a snapshot that starts at the moment the recording was started instead of when the agent was loaded?

**Comment by ingokegel** [comment]
Adding 

    invoke("startVMTelemetryRecording");

to `JProfilerController.startNow()` would clear the previous telemetry data. I'm not sure if that improves anything, though. The bookmarks in the telemetry views already show where the recording has started. Also, clearing the telemetry would not reset the time origin of the snapshot (this is currently not possible).

**Comment by oehme** [comment]
Thanks Ingo. The same is true for YourKit, so nothing we can change from the Gradle Profiler side.

**Comment by cesar1000** [comment]
Ah, I was meaning to ask about bookmarks - that certainly does the trick. By bookmarks do you mean the message events? I see the CPU sampling started/stopped event. Would it make sense to add other useful events from the chrome trace, like tasks starting?

**Comment by oehme** [comment]
That would only work when using method instrumentation, which adds a lot of overhead and skews the results. That being said, there is an open issue to support YourKit probes (#23), which would probably allow you to get this kind of more detailed info.

**Comment by cesar1000** [comment]
Why would you need method instrumentation though? Can't you use the same signals the chrome trace output is using? I generated both outputs in a single run of gradle-profiler, so I expected the traces in the chrome trace could just be added to the YourKit snapshot.

**Comment by oehme** [comment]
Oh I get it now, you'd inject logic that talks to the yourkit agent. Makes sense. Would you be interested to to look into this?

**Comment by cesar1000** [comment]
Sure, I can take a look.

**Comment by oehme** [comment]
Closing since there was no more development here.
