### ISSUE TITLE
Make profile output directory customizable

### ISSUE THREAD

**Issue by lamphama2** [gradle/gradle-profiler#543]
## Description
Currently, the benchmark output location is hard-coded to `/profile-out` folder. This lacks of flexibility and also the output directory depends on the location where we are executing the command.
Should we leave user an option to customize this location?

## Use case
- I want to give the output folder a specific name to differentiate different benchmarks. (I don't want do it manually after build).
- Launch different benchmark (not different scenarios) at the same time

## Expectation
Introduce a new optional option `--profile-out`, default it to the current value `profile-out`

**Comment by gabrielfeo** [comment]
You can use `--output-dir`:
> - `--output-dir <dir>`: Directory to write results to. Default value is profile-out. If profile-out directory already exists, it tries to find a `profile-out-<index>` directory, that does not exist.
>
> (from the [README](https://github.com/gradle/gradle-profiler?tab=readme-ov-file#command-line-options))

**Comment by lamphama2** [comment]
Oh sorry my bad
Closing this.
