### ISSUE TITLE
The profiler drops the jvm args that start with `-D` in the gradle.properties

### ISSUE THREAD

**Issue by pbreault** [gradle/gradle-profiler#55]
In an Android project, I am configuring the allocated memory for both the Gradle Daemon and the Kotlin Daemon.

The project's `gradle.properties` looks something like this:
```
org.gradle.jvmargs=-Xmx5g -Xms5g -Dkotlin.daemon.jvm.options=-Xmx8g,-Xms8g
```

the `-Dkotlin.daemon.jvm.options=-Xmx8g,-Xms8g` is completely ignored when I start a benchmark. The gradle memory settings  (-Xmx5g -Xms5g) are handled properly.

The expected behavior would be to have the profiler use the arguments defined in the `project.properties`

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle-profiler/commit/49be362fc37f434569485cdf49b4ab35c2f007d3
