### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by kevincianfarini** [gradle/gradle-profiler#565]
Hi all, some issues were fixed in #526 and #532 that allow profiling of Android Studio IDE sync on versions past Iguana. The current stable release of Android Studio is on Koala. Is there any way a new patch could be released that allows for people to profile on higher versions of AS without having to build `gradle-profiler` from source?

**Comment by asodja** [comment]
Gradle-profiler [0.21.0](https://github.com/gradle/gradle-profiler/releases/tag/v0.21.0) is out. 🎉
