### ISSUE TITLE
No chrome trace files generated in minimalistic Docker environment.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gradle/gradle-profiler#64]
Use-case: I run profiling in Docker to isolate local environment from JDK installation and make it reproducible across machines.

Problem is that `--profile chrome-trace` produces 0 html files if run in Docker container.

If I run it locally it works fine, I wonder if there are any system dependencies that I need to install for `chrome-trace`.

You can reproduce it by running: 

```console
scripts/profile-rxjava-docker-oracle-jdk8-chrome-trace.sh
```

On this repo: https://github.com/artem-zinnatullin/error-prone-performance

If you run gradle-profiler locally, it'll produce chrome-trace (tested on macOS and Linux)

```console
gradle-profiler --profile chrome-trace --warmups 1 --iterations 1 --project-dir rxjava --scenario-file scenarios/error-prone-jdk8.scenario
```

**Comment by oehme** [comment]
Chrome trace has no dependencies. Can you upload a profiling log? I won't have time to try out the docker image myself at the moment.

**Comment by oehme** [comment]
Closing since there was no more feedback. Feel free to reopen if you have more information, e.g. a profiling log.
