### ISSUE TITLE
Create JFR flame graphs on Java 9+

### ISSUE THREAD

**Issue by oehme** [gradle/gradle-profiler#77]

**Comment by javabrett** [comment]
It's probably already been noticed that as well as the lib jars being renamed, all the packages have been relocated from `com.jrockit.mc` to `com.oracle.jmc`.  Not sure which of the following options is preferred (all refer to oehme/jfr-flame-graph):

- Pre-shadow to a common package-name and check/hope for API stability.  Produce a JDK8 and JDK9 all version of that lib with the correct dependency.  Clearly the JFR recording format has changed.
- Split out the source and compile separately for JDK8 and JFK9, and produce different -all versions.  Downside is that two source-trees have to be independently maintained.

**Comment by javabrett** [comment]
Actually JDK9 is EOL but I imagine this applies to JDK10 also.

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle-profiler/commit/2db305f1aefbb9a627b05e894a416acdc03f19c8
