### ISSUE TITLE
Allow to mutate multiple files with one mutation 

### ISSUE THREAD

**Issue by NikitaKozlov** [gradle/gradle-profiler#85]
It might be very useful to change multiple files with a single mutation, for example change source files in different modules. Ideally I would love to write a scenario with something like this:
```
apply-abi-change-to = ["filePath1", "filePath2"]
```
Please, let me know if you are interested in the PR for this change. I tried it locally and I believe it is a fairly easy change.

**Comment by oehme** [comment]
Makes perfect sense, a PR is welcome :)

**Comment by oehme** [comment]
Fixed by #98
